import sqlite3 as lite
import sys

mh = lite.connect("mh-keyword.db")

with mh:
	cur = mh.cursor()
	cur.execute("DROP TABLE IF EXISTS Keyword_Table")
	cur.execute("CREATE TABLE Keyword_Table(Keyword TEXT)")
	cur.execute("INSERT INTO Keyword_Table VALUES('auto')")
	cur.execute("INSERT INTO Keyword_Table VALUES('break')")
	cur.execute("INSERT INTO Keyword_Table VALUES('case')")
	cur.execute("INSERT INTO Keyword_Table VALUES('char')")
	cur.execute("INSERT INTO Keyword_Table VALUES('const')")
	cur.execute("INSERT INTO Keyword_Table VALUES('continue')")
	cur.execute("INSERT INTO Keyword_Table VALUES('default')")
	cur.execute("INSERT INTO Keyword_Table VALUES('do')")
	cur.execute("INSERT INTO Keyword_Table VALUES('double')")
	cur.execute("INSERT INTO Keyword_Table VALUES('else')")
	cur.execute("INSERT INTO Keyword_Table VALUES('enum')")
	cur.execute("INSERT INTO Keyword_Table VALUES('extern')")
	cur.execute("INSERT INTO Keyword_Table VALUES('float')")
	cur.execute("INSERT INTO Keyword_Table VALUES('for')")
	cur.execute("INSERT INTO Keyword_Table VALUES('goto')")
	cur.execute("INSERT INTO Keyword_Table VALUES('if')")
	cur.execute("INSERT INTO Keyword_Table VALUES('int')")
	cur.execute("INSERT INTO Keyword_Table VALUES('long')")
	cur.execute("INSERT INTO Keyword_Table VALUES('register')")
	cur.execute("INSERT INTO Keyword_Table VALUES('return')")
	cur.execute("INSERT INTO Keyword_Table VALUES('short')")	
	cur.execute("INSERT INTO Keyword_Table VALUES('signed')")
	cur.execute("INSERT INTO Keyword_Table VALUES('sizeof')")
	cur.execute("INSERT INTO Keyword_Table VALUES('static')")
	cur.execute("INSERT INTO Keyword_Table VALUES('struct')")
	cur.execute("INSERT INTO Keyword_Table VALUES('switch')")
	cur.execute("INSERT INTO Keyword_Table VALUES('typedef')")
	cur.execute("INSERT INTO Keyword_Table VALUES('union')")
	cur.execute("INSERT INTO Keyword_Table VALUES('unsigned')")
	cur.execute("INSERT INTO Keyword_Table VALUES('void')")
	cur.execute("INSERT INTO Keyword_Table VALUES('volatile')")
	cur.execute("INSERT INTO Keyword_Table VALUES('while')")
	cur.execute("INSERT INTO Keyword_Table VALUES('include')")
	cur.execute("INSERT INTO Keyword_Table VALUES('main')")
	cur.execute("INSERT INTO Keyword_Table VALUES('uint8_t')")
	cur.execute("INSERT INTO Keyword_Table VALUES('uint16_t')")
	cur.execute("INSERT INTO Keyword_Table VALUES('uint32_t')")
	cur.execute("INSERT INTO Keyword_Table VALUES('uint64_t')")

	
	
